### ISSUE TITLE
Refactor installation role

### ISSUE THREAD

**Issue by piotrpersona** [piotrpersona/environment#10]
Move

```yaml
ubuntu.yml

when: {{ tool }}_status is failed
```

to main.yml block

```yaml
main.yml

when: {{ tool }}_status is failed
block:
  - include: ubuntu.yml
```
